version: 2.1
orbs:
    zulip: ponylang/zulip@1.0.0

jobs:
  vs-ponyc-release:
    docker:
      - image: ponylang/ponyc:release
    steps:
      - checkout
      - run: make test examples
      - zulip/status:
          fail_only: true
  vs-ponyc-master:
    docker:
      - image: ponylang/ponyc:latest
    steps:
      - run: apt-get update
      - run: apt-get install -y libpcre2-dev libssl-dev
      - checkout
      - run: make test examples
      - zulip/status:
          fail_only: true


workflows:
  version: 2
  commit:
    jobs:
      - vs-ponyc-master
  nightly-master:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
                - release
    jobs:
    - vs-ponyc-master:
        context: org-global
        filters:
          branches:
            only: master
    - vs-ponyc-release:
        context: org-global
        filters:
          branches:
            only: release
